language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
  - "pip install -r requirements-dev.txt"
  - "pip install pytest"
  - "python setup.py sdist"
  - "pip install dist/rasterio*.tar.gz"
script: py.test
