language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
  - pip install --install-option="--no-cython-compile" cython
  - "pip install -r requirements-dev.txt"
  - "pip install pytest pytest-cov"
  - "pip install coveralls"
  - "pip install -e ."
script: 
  - py.test -s --cov rasterio --cov-report term-missing
after_success:
  - coveralls
