language: python
python:
- '2.7'
- '3.3'
- '3.4'
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ppa
- sudo apt-get update -qq
- sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
- pip install -U pip
- pip install wheel
- pip wheel --wheel-dir=/tmp/wheelhouse -r requirements-dev.txt
- pip install --use-wheel --no-index --find-links=/tmp/wheelhouse cython numpy
- pip wheel --wheel-dir=/tmp/wheelhouse .
- pip install --use-wheel --no-index --find-links=/tmp/wheelhouse .
script:
- py.test --cov rasterio --cov-report term-missing
after_success:
- ls /tmp/wheelhouse
- coveralls
env:
  global:
  - secure: Y0xrKBKfvtdLrmNctU9F+nwBy8biYpzVti0wI+9hbcl4dsPLtvUuU9qF8fbP8BBjNRNJoLo2gnEhG+pz6MjoS+kL5ya5qCd6obrI21wVTT3zBEnDYGSIrWjzGB8uoBdPxnSN6y7jTZbCfCpYBipPSqhLn9l946gR4iDZzlz3KkM=
  - secure: yyCxK6M0084z0KQePyNEouQAbGfMehYD9KpVpkHgqWQ/VCtWSv+6QvM+Xb8CkzG13/JlZ0D1kAVjWzBGoXFB7GpXrjaunWBMbn6LMDbjh21mVlTrYGY2BZC5Ihy+B5IaxNf+tbmY78xzttyao2aXu4aK8x3WPfSkgjJq7rxbI4o=
