language: python
sudo: false
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
  matrix:
    - GDALVERSION="1.11.5"
    - GDALVERSION="2.0.3"
    - GDALVERSION="2.1.4"
    - GDALVERSION="2.2.1"
    - GDALVERSION="2.2.2"
    - GDALVERSION="2.2.3"
    - GDALVERSION="master"

matrix:
  allow_failures:
    - env: GDALVERSION="master"

addons:
  apt:
    packages:
    - gdal-bin
    - libproj-dev
    - libhdf5-serial-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
python:
  - "2.7"
  - "3.6"
before_script: # configure a headless display to test matplotlib
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
before_install:
  - pip install -U pip
  - pip install wheel
  - . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
install:
  - "if [ \"$GDALVERSION\" == \"master\" -o $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
  - "pip wheel -r requirements-dev.txt"
  - "pip install -r requirements-dev.txt"
  - "GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config pip install --upgrade --force-reinstall -e .[test,plot]"
  - "pip install coveralls>=1.1"
  - "rio --version"
  - "rio --gdal-version"
  - "pip list"
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.5 && $GDALVERSION == 2.1.0 ]]; then python -m pytest --doctest-ignore-import-errors --doctest-glob='*.rst' docs/*.rst -k 'not index and not quickstart and not switch' ; fi"
  - python -m pytest --cov rasterio --cov-report term-missing
after_success:
  - coveralls || echo "!! intermittent coveralls failure"
