dist: xenial

language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PROJINST=$HOME/gdalinstall
    - PROJBUILD=$HOME/projbuild

jobs:
  include:
    - python: "3.7"
      env:
        GDALVERSION="3.0.4"
        PROJVERSION="6.2.1"
    - python: "3.7"
      env:
        GDALVERSION="3.1.4"
        PROJVERSION="6.3.2"
    - python: "3.8"
      env:
        GDALVERSION="3.1.4"
        PROJVERSION="7.0.1"
    - python: "3.8"
      env:
        GDALVERSION="3.2.3"
        PROJVERSION="7.1.1"
    - python: "3.9"
      env:
        GDALVERSION="3.2.3"
        PROJVERSION="7.2.1"
    - python: "3.8"
      env:
        GDALVERSION="3.3.2"
        PROJVERSION="8.0.1"
    - python: "3.9"
      env:
        GDALVERSION="3.3.2"
        PROJVERSION="8.1.1"
    - python: "3.9"
      env:
        GDALVERSION="master"
        PROJVERSION="8.1.1"
  allow_failures:
    - env:
        GDALVERSION="master"
        PROJVERSION="8.1.1"

addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - python -m pip install -U pip
  - python -m pip install wheel
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - . ./scripts/travis_proj_install.sh
  - travis_wait 20 . ./scripts/travis_gdal_install.sh
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=$GDALINST/gdal-$GDALVERSION/share/proj

install:
  - "if [ \"$GDALVERSION\" == \"master\" -o $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
  - "python -m pip wheel -r requirements-dev.txt"
  - "python -m pip install -r requirements-dev.txt"
  - "python setup.py clean"
  - "GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install --no-deps --force-reinstall --no-use-pep517 -e .[test]"
  - "python -m pip install coveralls>=1.1"
  - "rio --version"
  - "rio --gdal-version"
  - "python -m pip list"

before_script:
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
  - aws sts get-caller-identity

script:
  - python -m pytest -v -m "not wheel" -rxXs --cov rasterio --cov-report term-missing

after_success:
  - coveralls || echo "!! intermittent coveralls failure"

cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
