language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
  - "pip install -r requirements-dev.txt"
  - "pip install pytest"
  - "pip install coveralls"
  - "pip install -e ."
script: 
  - py.test
  - coverage run --source=rasterio --omit='*.pxd,*.pyx,*/tests/*,*/docs/*,*/examples/*,*/benchmarks/*' -m py.test
after_success:
  - coveralls
