name: _rasterio
channels:
- conda-forge
dependencies:
- python=3.6.6
- libgdal=2.3.2
- alabaster==0.7.12
- asn1crypto==0.24.0
- babel==2.6.0
- cffi==1.12.2
- chardet==3.0.4
- cryptography==2.3.1
- docutils==0.14
- idna==2.8
- imagesize==1.1.0
- jinja2==2.10
- markupsafe==1.1.1
- mock==2.0.0
- olefile==0.46
- packaging==19.0
- pbr==5.1.3
- pillow==5.4.1
- pycparser==2.19
- pygments==2.3.1
- pyopenssl==19.0.0
- pyparsing==2.3.1
- pysocks==1.6.8
- pytz==2018.9
- requests==2.21.0
- six==1.12.0
- snowballstemmer==1.2.1
- sphinx==1.8.5
- sphinx_rtd_theme==0.4.3
- sphinxcontrib==1.0
- sphinxcontrib-websupport==1.1.0
- urllib3==1.24.1
